### PR TITLE
bug: add support fo 64k page size

### PR DESCRIPTION
**Pull request by rollandf**
cat /etc/redhat-release
Red Hat Enterprise Linux release 9.4 (Plow)

uname -r
5.14.0-427.13.1.el9_4.aarch64+64k

Needed modules:
kernel-64k-devel.aarch64
kernel-64k-modules.aarch64

### CODE REVIEW

**Comment by adrianchiris** [comment]
@rollandf can you provide more info in commit msg, what is the meaning of support 64k page size
i.e please mention the kernel version as appears in uname -r as well as the kernel packages that need to be installed.

**Comment by rollandf** [comment]
> @rollandf can you provide more info in commit msg, what is the meaning of support 64k page size i.e please mention the kernel version as appears in uname -r as well as the kernel packages that need to be installed.
> 
> it would help me do a review of this one :)

Sorry, about that. I added more info.

**Comment by rollandf** [comment]
```
26-Sep-24_12:00:35] NVIDIA driver container exec start
[26-Sep-24_12:00:35] OS is Red Hat
[26-Sep-24_12:00:35] [os-release]: NAME="Red Hat Enterprise Linux" VERSION="9.2 (Plow)" ID="rhel" ID_LIKE="fedora" VERSION_ID="9.2" PLATFORM_ID="platform:el9" PRETTY_NAME="Red Hat Enterprise Linux 9.2 (Plow)" ANSI_COLOR="0;31" LOGO="fedora-logo-icon" CPE_NAME="cpe:/o:redhat:enterprise_linux:9::baseos" HOME_URL="https://www.redhat.com/" DOCUMENTATION_URL="https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9" BUG_REPORT_URL="https://bugzilla.redhat.com/" REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 9" REDHAT_BUGZILLA_PRODUCT_VERSION=9.2 REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux" REDHAT_SUPPORT_PRODUCT_VERSION="9.2"
[26-Sep-24_12:00:35] [uname -a]: Linux co-node-38.maas 5.14.0-427.13.1.el9_4.aarch64+64k #1 SMP PREEMPT_DYNAMIC Wed Apr 10 15:34:42 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux

```


....


```
[26-Sep-24_12:00:35] Function: redhat_fetch_major_ver
[26-Sep-24_12:00:35] Executing command: egrep "^ID=|^VERSION_ID=|^RHEL_VERSION=" /host/etc/os-release
ID="rhel"
VERSION_ID="9.4"
declare -- ID="rhel"
declare -- VERSION_ID="9.4"
[26-Sep-24_12:00:35] RHEL major version: 9
[26-Sep-24_12:00:35] Installing dependencies
[26-Sep-24_12:00:35] 64k page size kernel identified
[26-Sep-24_12:00:35] Executing command: cp /host/etc/yum.repos.d/redhat.repo /etc/yum.repos.d/

[26-Sep-24_12:00:35] Executing command: dnf -q -y install kernel-64k-devel-5.14.0-427.13.1.el9_4.aarch64

Installed:
  bison-3.7.4-5.el9.aarch64                                                     
  elfutils-libelf-devel-0.188-3.el9.aarch64                                     
  flex-2.6.4-9.el9.aarch64                                                      
  kernel-64k-devel-5.14.0-427.13.1.el9_4.aarch64                                
  openssl-devel-1:3.0.7-17.el9_2.aarch64                                        
  zlib-devel-1.2.11-39.el9.aarch64                                              
[26-Sep-24_12:01:20] Executing command: dnf -q -y install kernel-64k-modules-5.14.0-427.13.1.el9_4.aarch64

Installed:
  kernel-64k-core-5.14.0-427.13.1.el9_4.aarch64                                 
  kernel-64k-modules-5.14.0-427.13.1.el9_4.aarch64                              
  kernel-64k-modules-core-5.14.0-427.13.1.el9_4.aarch64                         
  linux-firmware-20240716-143.2.el9_4.noarch                                    
  linux-firmware-whence-20240716-143.2.el9_4.noarch                             
[26-Sep-24_12:02:05] Executing command: dnf -q -y --releasever=9.4 install elfutils-libelf-devel kernel-rpm-macros numactl-libs lsof rpm-build patch hostname

Upgraded:
  elfutils-debuginfod-client-0.190-2.el9.aarch64                                
  elfutils-libelf-0.190-2.el9.aarch64                                           
  elfutils-libelf-devel-0.190-2.el9.aarch64                                     
  elfutils-libs-0.190-2.el9.aarch64                                             
  python3-rpm-4.16.1.3-29.el9.aarch64                                           
  rpm-4.16.1.3-29.el9.aarch64                                                   
  rpm-build-libs-4.16.1.3-29.el9.aarch64                                        
  rpm-libs-4.16.1.3-29.el9.aarch64                                              
  rpm-sign-libs-4.16.1.3-29.el9.aarch64                                         
Installed:
  bzip2-1.0.8-8.el9.aarch64               debugedit-5.0-5.el9.aarch64          
  ed-1.14.2-12.el9.aarch64                elfutils-0.190-2.el9.aarch64         
  gdb-minimal-10.2-13.el9.aarch64         info-6.7-15.el9.aarch64              
  kernel-rpm-macros-185-13.el9.noarch     libtirpc-1.3.3-8.el9_4.aarch64       
  libzstd-devel-1.5.1-2.el9.aarch64       lsof-4.94.0-3.el9.aarch64            
  numactl-libs-2.0.16-3.el9.aarch64       patch-2.7.6-16.el9.aarch64           
  python-rpm-macros-3.9-53.el9.noarch     python3-packaging-20.9-5.el9.noarch  
  python3-rpm-generators-12-9.el9.noarch  python3-rpm-macros-3.9-53.el9.noarch 
  rpm-build-4.16.1.3-29.el9.aarch64       zstd-1.5.1-2.el9.aarch64             
Updating Subscription Management repositories.
Unable to read consumer identity
Subscription Manager is operating in container mode.

This system is not registered with an entitlement server. You can use subscription-manager to register.

Red Hat Enterprise Linux 9 for ARM 64 - AppStream (RPMs)                                                          8.3 kB/s | 4.5 kB     00:00    
Red Hat Enterprise Linux 9 for ARM 64 - BaseOS (RPMs)                                                             4.8 kB/s | 4.1 kB     00:00    
Red Hat Universal Base Image 9 (RPMs) - BaseOS                                                                     62 kB/s | 3.8 kB     00:00    
Red Hat Universal Base Image 9 (RPMs) - AppStream                                                                  79 kB/s | 4.2 kB     00:00    
Red Hat Universal Base Image 9 (RPMs) - CodeReady Builder                                                          66 kB/s | 3.8 kB     00:00    
Metadata cache created.
[26-Sep-24_12:02:24] Function: build_driver_from_src
[26-Sep-24_12:02:24] Starting driver build
[26-Sep-24_12:02:24] Executing command: /run/mellanox/src/MLNX_OFED_SRC-24.07-0.6.0.0/install.pl --without-depcheck --kernel 5.14.0-427.13.1.el9_4.aarch64+64k --kernel-only --build-only --with-mlnx-tools --without-knem --without-iser --without-isert --without-srp --without-kernel-mft --without-mlnx-rdma-rxe --without-mlnx-nfsrdma --without-mlnx-nvme --disable-kmp
Logs dir: /tmp/OFED.22527.logs
General log file: /tmp/OFED.22527.logs/general.log

```

**Review by almaslennikov — APPROVED** [review]

**Review by e0ne — APPROVED** [review]
LGTM

**Pull request merged**
